services:
  - type: web
    name: quanvitlonmanager
    env: docker
    plan: free
    buildCommand: docker build -t quanvitlonmanager .
    startCommand: docker run -p $PORT:80 quanvitlonmanager
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: quanvitlon_db
          property: connectionString

databases:
  - name: quanvitlon_db
    plan: free
    ipAllowList: []
