services:
  - type: web
    name: vitlon-manager
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vitlon-database
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

databases:
  - name: vitlon-database
    plan: free
    databaseName: vitlondb
    user: vitlonuser 